#!/usr/bin/gst -g

   db := Dictionary new.
   db at:'j2' put:'HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu ';
      at:'j3' put:'HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr ';
      at:'j5' put:'PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb ';
      at:'j6' put:'HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp ';
      at:'k1' put:'____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ';
      at:'k2' put:'NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ';
      at:'k5' put:'UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ';
      at:'k6' put:'HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi ';
      at:'n0' put:'HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb ';
     at:'j17' put:'____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ';
     at:'j23' put:'HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu ';
     at:'j25' put:'FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb ';
     at:'j26' put:'HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ';
     at:'j36' put:'HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp ';
     at:'j56' put:'UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb ';
     at:'k12' put:'____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ';
     at:'k15' put:'____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ';
     at:'k25' put:'NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ';
     at:'k26' put:'HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu ';
     at:'k34' put:'PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb ';
     at:'k56' put:'HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp ';
    at:'j236' put:'HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu ';
    at:'j256' put:'FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb ';
    at:'j2k5' put:'FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb ';
    at:'j2k6' put:'HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu ';
    at:'j2y3' put:'HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu ';
    at:'j3k5' put:'NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb ';
    at:'j3k6' put:'HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe ';
    at:'j5y6' put:'PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb ';
    at:'k125' put:'____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ';
    at:'k1j5' put:'____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ';
    at:'k1j6' put:'____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ';
    at:'k256' put:'HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu ';
    at:'k2j5' put:'NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ';
    at:'k2j6' put:'HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu ';
    at:'k2x1' put:'____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ';
    at:'k6x5' put:'HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi ';
    at:'n167' put:'NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb ';
    at:'n345' put:'____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ';
    at:'n5y2' put:'HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu ';
    at:'n6x2' put:'FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ ';
   at:'j17k2' put:'____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ';
   at:'j17y2' put:'HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ';
   at:'j23k6' put:'HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu ';
   at:'j25y6' put:'TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb ';
   at:'j26y3' put:'HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu ';
   at:'j2k34' put:'TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb ';
   at:'j2k56' put:'HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu ';
   at:'j34k6' put:'HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn ';
   at:'j56y7' put:'UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ ';
   at:'k12j5' put:'____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ';
   at:'k17j5' put:'TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ____ ';
   at:'k25x1' put:'____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ';
   at:'k26x5' put:'HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ';
   at:'k2j56' put:'NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb ';
   at:'k34x2' put:'PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb ';
   at:'k56x4' put:'HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp ';
   at:'n25x6' put:'TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb ';
   at:'n26y5' put:'____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ';
   at:'n45y2' put:'HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe ';
   at:'n67x2' put:'____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ';
  at:'j136y7' put:'____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ';
  at:'j167y2' put:'HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp ';
  at:'j246y3' put:'HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu ';
  at:'j26y34' put:'HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu ';
  at:'j2k6x5' put:'HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu ';
  at:'j2k6y3' put:'HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu ';
  at:'j346y5' put:'NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb ';
  at:'j3k5x4' put:'HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp ';
  at:'k135x4' put:'____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ';
  at:'k157x6' put:'HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu ';
  at:'k1j6y7' put:'____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ';
  at:'k257x1' put:'NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ';
  at:'k25x17' put:'____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ';
  at:'k2j5x1' put:'____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ';
  at:'k2j5y6' put:'NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb ';
  at:'k345x2' put:'UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb ';
  at:'n167x4' put:'HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ';
  at:'n345y7' put:'____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ';
 at:'j2k56x4' put:'HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu ';
 at:'j3k56x4' put:'HgTi ____ SnNp UrAu ____ ____ ____ AuUr NpSn ____ TiHg FeFe ';
 at:'k1j56y7' put:'____ AuUr NpSn ____ TiHg FeFe HgTi ____ SnNp UrAu ____ ____ ';
 at:'k2j56y7' put:'NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ '.

Transcript show: ''; cr.

(db keys asSortedCollection) do: [ :qp |
  Transcript show: qp, '-beadgcf'; cr.

  "Fn"
  Transcript show: ((db at: qp) copyFrom:26 to:60),
                   ((db at: qp) copyFrom: 1 to:25); cr.
  "Cn"
  Transcript show: ((db at: qp) copyFrom: 1 to:60); cr.

  "Gn"
  Transcript show: ((db at: qp) copyFrom:36 to:60),
                   ((db at: qp) copyFrom: 1 to:35); cr.
  "Dn"
  Transcript show: ((db at: qp) copyFrom:11 to:60),
                   ((db at: qp) copyFrom: 1 to:10); cr.
  "An"
  Transcript show: ((db at: qp) copyFrom:46 to:60),
                   ((db at: qp) copyFrom: 1 to:45); cr.
  "En"
  Transcript show: ((db at: qp) copyFrom:21 to:60),
                   ((db at: qp) copyFrom: 1 to:20); cr.
  "Bn"
  Transcript show: ((db at: qp) copyFrom:56 to:60),
                   ((db at: qp) copyFrom: 1 to:55); cr.

  Transcript show: ''; cr.
]

